name: 'skinsly'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skinsly
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "55432:5432"

  redis:
    image: redis:8.0-M03
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: